# Generated by Django 2.2.4 on 2019-12-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.FloatField(blank=True, null=True)),
                ('Y', models.FloatField(blank=True, null=True)),
                ('Unique_Squirrel_ID', models.CharField(max_length=20, null=True)),
                ('Shift', models.CharField(blank=True, choices=[('AM', 'In the morning'), ('PM', 'In the afternoon')], default='AM', max_length=20, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Age', models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile'), ('Unknown', '?'), ('', '')], default='', max_length=20, null=True)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnammon', 'Cinnammon'), ('', ''), ('     ', '?')], default='', max_length=20, null=True)),
                ('Highlight_Fur_Color', models.CharField(blank=True, choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnammon', 'Cinnammon'), ('White', 'White'), ('Black, Cinnammon', 'Black, Cinnammon'), ('Black, White', 'Black, White'), ('Black, Cinnammon, White', 'Black, Cinnammon, White'), ('Cinnammon, White', 'Cinammon, White'), ('Gray, Black', 'Gray, Black'), ('Black, White', 'Black, White'), ('Gray, White', 'Gray, White'), ('?', '?'), ('', '')], default='', max_length=50, null=True)),
                ('Combination_Fur', models.CharField(blank=True, max_length=100, null=True)),
                ('Color_Notes', models.CharField(blank=True, max_length=100, null=True)),
                ('Location', models.CharField(blank=True, choices=[('Above Ground', 'Above Ground'), ('Ground Plane', 'Ground Plane'), ('?', '?'), ('', '')], default='', max_length=20, null=True)),
                ('Above_Ground_Sighter_Measurement', models.CharField(blank=True, default='FALSE', max_length=20, null=True)),
                ('Specific_Location', models.CharField(blank=True, max_length=100, null=True)),
                ('Running', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Chasing', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Climbing', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Eating', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Foraging', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Other_Activities', models.CharField(blank=True, max_length=100, null=True)),
                ('Kuks', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Quaas', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Moans', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Tail_Flags', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Tail_Twitches', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Approaches', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Indifferent', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Runs_From', models.CharField(blank=True, choices=[('TRUE', 'true'), ('FALSE', 'false')], default='FALSE', max_length=10, null=True)),
                ('Other_Interactions', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
